### ISSUE TITLE
Build fail for SDK 28

### ISSUE THREAD

**Issue by cristianoccazinsp** [prscX/react-native-photo-editor#58]
https://github.com/prscX/react-native-photo-editor/blob/master/android/src/main/java/com/ahmedadeltito/photoeditor/widget/SlidingUpPanelLayout.java#L1187

node_modules/react-native-photo-editor/android/src/main/java/com/ahmedadeltito/ph
otoeditor/widget/SlidingUpPanelLayout.java:1187: error: cannot find symbol
        final int save = canvas.save(Canvas.CLIP_SAVE_FLAG);

The above uses something removed in Android P

**Comment by d2luu** [comment]
Fixed in this [PR](https://github.com/prscX/react-native-photo-editor/pull/54/commits/89fd29465f8f9a2883d3ddbf407c15ebbdf75658)

**Comment by babakansari** [comment]
@d2luu - Do you know if the fix is included into the latest `react-native-photo-editor` package?

**Comment by d2luu** [comment]
@babakansari - It seems to this PR still not merged to master branch. So the fix is not reflected into the latest `react-native-photo-editor` package yet.
@prscX - Can you verify it?

**Comment by babakansari** [comment]
@prscX - Yes, it's not been merged yet. I forked the fix:
`yarn add prscX/react-native-photo-editor#54/head`
Thanks!

**Comment by prscX** [comment]
Thanks @d2luu for the Effort and PR.

@cristianoccazinsp: Could you please install latest version and migrate your app to RN61. Please follow installation steps defined in `README` . Let me know incase it still does not work.

Thanks
</ Pranav >
